config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener' # letter_opener_webのルーティング設定
    mount Sidekiq::Web, at: '/sidekiq' # sidekiqのルーティング設定
  end
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[index new create show]

  # :shallowオプションを指定するとedit・show・update・destroyのアクション（idを必要とするアクション）のエンドポイントとヘルパーメソッドがスッキリする（浅いネスト）
  resources :posts, shallow: true do
    collection { get :search } # postsコントローラーのsearchアクション、エンドポイントは /posts/search
    resources :comments
  end
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do # only: に空配列を指定することで /activities/:id/read というエンドポイントのみ作成している
    patch :read, on: :member # member do patch :read end と同じ意味
  end

  # /mypage/account/〜となるようにルーティング設定
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end

  root 'posts#index'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_comments_on_post_id  (post_id)
#  index_comments_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (post_id => posts.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_one :activity, as: :subject, dependent: :destroy # ポリモーフィック関連づけ

  validates :body, presence: true, length: { maximum: 1000 } # コメント文字数が1000文字を超えるとバリデーションに引っかかるよう設定

  after_create_commit :create_activities # コールバックを用いてCommentのレコードが作られたときにcreate_activitiesメソッドを呼び出す。つまり、コメントされたらActivityのレコードも作られる。

  private

  def create_activities
    Activity.create(subject: self, user: post.user, action_type: :commented_to_own_post)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: %i[create edit update destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save && @comment.post.user.notification_on_comment?
      # コメントされ、なおかつ通知をONにしている場合に以下の処理を実行
      UserMailer.with(
        # mialerには以下の引数を渡している
        user_from: current_user,
        user_to: @comment.post.user,
        comment: @comment,
      ).comment_post # user_mailer.rbのcomment_postメソッドを実行
        .deliver_later # 非同期でメールを送信
    end
  end

  def edit
    @comment = current_user.comments.find(params[:id])
  end

  def update
    @comment = current_user.comments.find(params[:id])
    @comment.update(comment_update_params)
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end

  def comment_update_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.slim
div id="comment-#{comment.id}"
  .row.no-gutters
    .col-2
      = image_tag comment.user.avatar.url, size: '40x40', class: 'rounded-circle'
    .col-9
      span.font-weight-bold.pr-1
        = comment.user.username
      = comment.body
    .col-1
      - if current_user&.own?(comment)
        = link_to comment_path(comment), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'}, remote: true do
            = icon 'far', 'trash-alt', class: 'fa-sm'
        / Ajax通信でcommentコントローラーのeditメソッドを実行
        = link_to edit_comment_path(comment), remote: true do
          = icon 'far', 'edit', class: 'fa-sm'
  hr

app/views/comments/_comments.html.slim
.comments-box
  / render partial: 'comment', collection: comments と同じ意味
  = render comments

app/views/comments/_form.html.slim
/ form_withでlocal: true を指定していないのでAjax通信になる。commentsコントローラーのcreateアクション実行後にapp/views/comments/create.js.slimが実行される。
= form_with model: [post, comment], class: 'd-flex mb-0 flex-nowrap justify-content-between' do |f|
  = f.text_field :body, class: 'form-control input-comment-body', placeholder: 'コメント'
  = f.submit '投稿', class: 'btn btn-primary btn-raised'

app/views/comments/_modal_form.html.slim
.modal#comment-edit-modal
  .modal-dialog
    .modal-content
      .modal-header
        h5.modal-title コメント編集
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
      .modal-body
        / app/views/comments/_form.html.slimのパーシャルを呼び出しているがpostの値は不要の為nilを代入
        = render 'form', post: nil, comment: comment

app/views/comments/create.js.slim
/ commentsコントローラーのcreateアクションでバリデーションに引っかかる場合とそうでない場合の非同期処理を実装
- if @comment.errors.present?
  / もしバリデーションに引っかかった場合、ブラウザのアラートにメッセージにエラーメッセージの後に開業を入れて表示する
  | alert("#{@comment.errors.full_messages.join('\n')}");
- else
  / comment-boxクラスの中の一番上に新規コメントを追加する
  | $('.comments-box').prepend("#{j render('comments/comment', comment: @comment)}");
  / コメント入力欄を空欄にする
  | $('.input-comment-body').val('');

app/views/comments/destroy.js.slim
/ コメントを削除
| $('#comment-#{@comment.id}').remove()

app/views/comments/edit.js.slim
/ app/views/shared/_modal.html.slimの#modal-containerの内側にapp/views/comments/_modal_form.html.slimを呼び出す
| $("#modal-container").html("#{escape_javascript(render 'modal_form', comment: @comment)}");
/ モーダルを開く
| $("#comment-edit-modal").modal('show');

app/views/comments/update.js.slim
- if @comment.errors.present?
  | alert("#{@comment.errors.full_messages.join('\n')}");
- else
  / もしコメント更新時にバリデーションにひっかからなかったらコメントの内容を書き換える
  | $("#comment-#{@comment.id}").html("#{j render('comments/comment', comment: @comment)}");
  / モーダルを閉じる
  | $("#comment-edit-modal").modal('hide');