config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener' # letter_opener_webのルーティング設定
    mount Sidekiq::Web, at: '/sidekiq' # sidekiqのルーティング設定
  end
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[index new create show]

  # :shallowオプションを指定するとedit・show・update・destroyのアクション（idを必要とするアクション）のエンドポイントとヘルパーメソッドがスッキリする（浅いネスト）
  resources :posts, shallow: true do
    collection { get :search } # postsコントローラーのsearchアクション、エンドポイントは /posts/search
    resources :comments
  end
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do # only: に空配列を指定することで /activities/:id/read というエンドポイントのみ作成している
    patch :read, on: :member # member do patch :read end と同じ意味
  end

  # /mypage/account/〜となるようにルーティング設定
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end

  root 'posts#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :bigint           not null, primary key
#  avatar                  :string(255)
#  crypted_password        :string(255)
#  email                   :string(255)      not null
#  notification_on_comment :boolean          default(TRUE)
#  notification_on_follow  :boolean          default(TRUE)
#  notification_on_like    :boolean          default(TRUE)
#  salt                    :string(255)
#  username                :string(255)      not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
# Indexes
#
#  index_users_on_email     (email) UNIQUE
#  index_users_on_username  (username) UNIQUE
#

# Sorceryのジェネレータによって自動生成されたUserモデル

class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader # avatarカラムとAvatarUploaderクラスを紐付け

  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true

  # Sorceryを使ったパスワードのバリデーション
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  has_many :posts, dependent: :destroy # 親モデルを削除する場合に紐づく子モデルを一緒に削除できるよう設定
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy # likeモデルと関連付け
  has_many :like_posts, through: :likes, source: :post # likeしたpostを取得できる、like_postsという関連名で利用できる
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy # relationshipsへの関連名をactive_relationshipsとして宣言、外部キーをfollower_idに設定
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy # relationshipsへの関連名をpassive_relationshipsとして宣言、外部キーをfollowed_idに設定
  has_many :following, through: :active_relationships, source: :followed # フォローしているユーザーの集合を取得できるようactive_relationshipsメソッドを設定
  has_many :followers, through: :passive_relationships, source: :follower # フォローされているユーザーの集合を取得できるようpassive_relationshipsメソッドを設定
  has_many :activities, dependent: :destroy # activityモデルに関連づけ

  scope :recent, ->(count) { order(created_at: :desc).limit(count) } # インスタンスを新規作成順に並べてcountの数だけ取得して返す

  # ユーザーが自身の子モデルのオブジェクトかどうかをを判定するメソッド
  def own?(object)
    id == object.user_id
  end

  # 中間テーブルであるlikesテーブルに引数で渡されたpostを新たなレコードとして加える。Like.create!(post_id: post.id, user_id: post.user.id)と同じ意味。
  def like(post)
    like_posts << post
  end

  # like_postsから引数で渡されたpostを削除
  def unlike(post)
    like_posts.destroy(post)
  end

  # like_postsの中に引数で渡されたpostが含まれているか否かをbooleanで返す
  def like?(post)
    like_posts.include?(post)
  end

  # フォローしているユーザの集合に引数で受け取ったother_userを加える
  def follow(other_user)
    following << other_user
  end

  # relationshipsテーブルから引数で受け取ったother_userを削除、結果的にアンフォローする
  def unfollow(other_user)
    following.destroy(other_user)
  end

  # followingの中に引数で渡されたpostが含まれているか否かをbooleanで返す、フォローしているかどうかを調べる
  def following?(other_user)
    following.include?(other_user)
  end

  # フォローしているユーザーのidと自身のidの投稿の一覧を取得して返している
  def feed
    Post.where(user_id: following_ids << id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).order(created_at: :desc) # ユーザモデルのインスタンスを取得、ページネーションを設定、新しいユーザから順に並び替え
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user) # 引数で指定したユーザにログインするSorcery独自のメソッド
      redirect_to login_path, success: 'ユーザーを作成しました'
    else
      flash.now[:danger] = 'ユーザーの作成に失敗しました'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params
      .require(:user)
      .permit(:email, :password, :password_confirmation, :username)
  end
end

app/views/users/_follow.html.slim
/ relationships#createがAjax通信で実行される
= link_to relationships_path(followed_id: user.id), class: 'btn btn-raised btn-outline-warning', method: :post, remote: true do
  | フォロー

app/views/users/_follow_area.html.slim
/ ログインしている場合のみ、なおかつ自分以外のユーザのみ表示される
- if logged_in? && current_user.id != user.id
  div id="follow-area-#{user.id}"
    / 既にフォローしているか否かで表示するパーシャルを変更
    - if current_user.following?(user)
      = render 'users/unfollow', user: user
    - else
      = render 'users/follow', user: user

app/views/users/_unfollow.html.slim
/ relationships#destroyがAjax通信で実行される
= link_to relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), class: 'btn btn-warning btn-raised', method: :delete, remote: true do
  | アンフォロー

app/views/users/_user.html.slim
.user.mb-3.d-flex.justify-content-between
  / ユーザ詳細ページへのリンク
  = link_to user_path(user) do
    = image_tag user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
    = user.username
  hr

app/views/users/index.html.slim
/ titleタグにmeta-tagsが優先される
- set_meta_tags title: 'ユーザー一覧ページ'
.container
  .row
    .col-md-6.col-12.offset-md-3.mb-3
      .card
        .card-body
          / app/views/users/_user.html.slimのパーシャルをuserインスタンスの数だけ表示
          = render @users
    .col-md-6.col-12.offset-md-3
      / ページネーションを表示
      = paginate @users

app/views/users/new.html.slim
/ titleタグにmeta-tagsが優先される
- set_meta_tags title: 'ユーザー登録ページ'
.login-register-form
  .login-register-form-inner
    .card.mb-3
      = form_with model: @user, class: 'card-body', local: true, id: 'signup_form' do |f|
        = render 'shared/error_messages', object: @user
        .form-group
          = f.label :username, class: 'bmd-label-floating'
          = f.text_field :username, class: 'form-control'
        .form-group
          = f.label :email, class: 'bmd-label-floating'
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :password, class: 'bmd-label-floating'
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation, class: 'bmd-label-floating'
          = f.password_field :password_confirmation, class: 'form-control'

        = f.submit '登録', class: 'btn btn-raised btn-primary'
    .card
      .card-body
        | アカウントをお持ちですか
        = link_to 'ログインする', login_path

app/views/users/show.html.slim
/ titleタグにmeta-tagsが優先される
- set_meta_tags title: 'ユーザー詳細ページ'
.container
  .row
    .col-md-10.offset-md-1
      .card
        .card-body
          / 自分のページだった場合にプロフィール編集画面へのリンクを表示させる
          / current_user&.idとしないとcurrent_userがnilだったときにエラーになる
          - if current_user&.id == @user.id
              .text-center.mb-3
                = link_to 'プロフィール編集', edit_mypage_account_path, class: 'btn btn-raised btn-warning'
          .text-center.mb-3
            = image_tag @user.avatar.url, size: '100x100', class: 'rounded-circle mr-1'
          .profile.text-center.mb-3
            = @user.username
          .text-center
            / app/views/users/_follow_area.html.slimのパーシャルを表示
            = render 'follow_area', user: @user
          hr
          .row
            /  postsの数だけapp/views/posts/_thumbnail_post.html.slimのパーシャルを表示。
            / モデルクラスのインスタンスに対して繰り返し処理をする場合はeachメソッドでループするよりもcollectionを使った方がパフォーマンスが良い。
            = render partial: 'posts/thumbnail_post', collection: @user.posts