config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener' # letter_opener_webのルーティング設定
    mount Sidekiq::Web, at: '/sidekiq' # sidekiqのルーティング設定
  end
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[index new create show]

  # :shallowオプションを指定するとedit・show・update・destroyのアクション（idを必要とするアクション）のエンドポイントとヘルパーメソッドがスッキリする（浅いネスト）
  resources :posts, shallow: true do
    collection { get :search } # postsコントローラーのsearchアクション、エンドポイントは /posts/search
    resources :comments
  end
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do # only: に空配列を指定することで /activities/:id/read というエンドポイントのみ作成している
    patch :read, on: :member # member do patch :read end と同じ意味
  end

  # /mypage/account/〜となるようにルーティング設定
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end

  root 'posts#index'
end

app/views/shared/_before_login_header.html.slim
/ ログイン状態ではないとき用のヘッダー部分のパーシャル

nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstagramClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    / app/views/posts/_search_form.html.slimのパーシャルを利用
    = render 'posts/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to 'ポスト一覧', posts_path, class: 'nav-link'
      li.nav-item
        = link_to 'ログイン', login_path, class: 'nav-link'

app/views/shared/_commented_to_own_post.html.slim
/ activitiesコントローラーのreadアクションを実行するリンク、通知が既読であればclassにreadを付ける
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do
  / コメントしたユーザのアバターを表示
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  / コメントしたユーザの詳細ページのリンクを表示
  object
    = link_to activity.subject.user.username, user_path(activity.subject.user)
  | があなたの
  / コメントされた投稿の詳細ページのリンク
  object
    = link_to '投稿', post_path(activity.subject.post)
  | に
  / アンカーリンクによってコメントの箇所を表示するリンク
  object
    = link_to 'コメント', post_path(activity.subject.post, anchor: "comment-#{activity.subject.id}")
  | しました
  .ml-auto
    / 通知が作成された日時を表示
    = l activity.created_at, format: :short

app/views/shared/_error_messages.html.slim
/ バリデーションに引っかかった場合のエラーメッセージ表示用のパーシャル

- if object.errors.any?
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
/ フラッシュメッセージ表示用のパーシャル

- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_followed_me.html.slim
/ activitiesコントローラーのreadアクションを実行するリンク、通知が既読であればclassにreadを付ける
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do
  / フォローをしたユーザのアバターを表示
  = image_tag activity.subject.follower.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  / フォローをしたユーザの詳細ページのリンクを表示
  object
    = link_to activity.subject.follower.username, user_path(activity.subject.follower)
  | があなたをフォローしました
  .ml-auto
    / 通知が作成された日時を表示
    = l activity.created_at, format: :short

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstagramClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    / app/views/posts/_search_form.html.slimのパーシャルを利用
    = render 'posts/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to new_post_path, class: 'nav-link' do
          = icon 'far', 'image', class: 'fa-lg'
      li.nav-item
        .dropdown
          / ドロップダウンメニューのボタン。data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"などを属性はドロップダウンメニューのために必要。
          a#dropdownMenuButton.nav-link.position-relative href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"
            = icon 'far', 'heart', class: 'fa-lg'
            / app/views/shared/_unread_badge.html.slimのパーシャル
            = render 'shared/unread_badge'
          / ドロップダウンメニューで表示されるメニュー部分。aria-labelledby="dropdownMenuButton"の属性はドロップダウンメニューのために必要。
          #header-activities.dropdown-menu.dropdown-menu-right.m-0.p-0 aria-labelledby="dropdownMenuButton"
            / app/views/shared/_header_activities.html.slimのパーシャルを埋め込み
            = render 'shared/header_activities'

      li.nav-item
        / a.nav-link href="#"
        = link_to user_path(current_user), class: 'nav-link' do
          = icon 'far', 'user', class: 'fa-lg'
      li.nav-item
        = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete

app/views/shared/_header_activities.html.slim
- if current_user.activities.present?
  / カレントユーザ宛に通がある場合の処理
  / recentスコープにより10件の通知を降順で表示
  - current_user.activities.recent(10).each do |activity|
    / activityモデルのaction_typeカラムの中身によって埋め込むパーシャルを変更している。
    = render "shared/#{activity.action_type}", activity: activity
  / 通知が10件以上ある場合は通知一覧ページへのリンクを表示
  - if current_user.activities.count > 10
    = link_to 'すべてみる', mypage_activities_path, class: 'dropdown-item justify-content-center'
- else
  / カレントユーザ宛に通がない場合の処理
  .dropdown-item
    | お知らせはありません

app/views/shared/_liked_to_own_post.html.slim
/ activitiesコントローラーのreadアクションを実行するリンク、通知が既読であればclassにreadを付ける
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do
  / いいねをしたユーザのアバターを表示
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  / いいねをしたユーザの詳細ページのリンクを表示
  object
    = link_to activity.subject.user.username, user_path(activity.subject.user)
  | があなたの
   / いいねをされた投稿の詳細ページのリンク
   object
    = link_to '投稿', post_path(activity.subject.post)
  | にいいねしました
  .ml-auto
    / 通知が作成された日時を表示
    = l activity.created_at, format: :short

app/views/shared/_modal.html.slim
#modal-container

app/views/shared/_unread_badge.html.slim
/ 読んでいない通知が1つ以上あれば、読んでいない件数を表示させる
- if current_user.activities.unread.count > 0
  span.badge.badge-warning.navbar-badge.position-absolute style='top: 0; right:0;'
    = current_user.activities.unread.count